- name: Configuring newly created EC2 instances
  hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      # wait_for_connection:
      #   timeout: 300

    - name: "install python for Ansible."
      # become: true
      # raw: test -e /user/bin/python3 || (apt -y update && apt install -y python3)
      # changed_when: false
  roles:
    # - role: setup
    # - role: configure_node_exporter
    # # - role: weareinteractive.environment
    # #   become: true

